server:
  port: 8080
mybatis:
  type-aliases-package: com.cqupt.demo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: AaAa123!
    initialization-mode: always

  mail:
    username: 发送邮件邮箱
    password: 授权码
    host: smtp.qq.com
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
