mybatis:
  type-aliases-package: com.cqupt.demo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.214.211:3306/demo?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: AaAa123!
    initialization-mode: always
  mail:
    username: xxx@qq.com
    password: xxxxxx
    host: smtp.qq.com
    port: 465
    default-encoding: UTF-8
    protocol: smtps
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

server:
  port: 443
  ssl:
    key-store: classpath:4337898_www.zhray.top.pfx
    key-store-type: PKCS12
    enabled: true
    key-store-password: E73e3Ec4


